# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10user_types.proto\x12\x05users\")\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\r\"W\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\r\"-\n\x10\x43reateUserResult\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\",\n\x0fGetUsersRequest\x12\x19\n\x04user\x18\x01 \x03(\x0b\x32\x0b.users.User\"+\n\x0eGetUsersResult\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.Userb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_CREATEUSERRESULT = DESCRIPTOR.message_types_by_name['CreateUserResult']
_GETUSERSREQUEST = DESCRIPTOR.message_types_by_name['GetUsersRequest']
_GETUSERSRESULT = DESCRIPTOR.message_types_by_name['GetUsersResult']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_types_pb2'
  # @@protoc_insertion_point(class_scope:users.User)
  })
_sym_db.RegisterMessage(User)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'user_types_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResult = _reflection.GeneratedProtocolMessageType('CreateUserResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERRESULT,
  '__module__' : 'user_types_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserResult)
  })
_sym_db.RegisterMessage(CreateUserResult)

GetUsersRequest = _reflection.GeneratedProtocolMessageType('GetUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSREQUEST,
  '__module__' : 'user_types_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUsersRequest)
  })
_sym_db.RegisterMessage(GetUsersRequest)

GetUsersResult = _reflection.GeneratedProtocolMessageType('GetUsersResult', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRESULT,
  '__module__' : 'user_types_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUsersResult)
  })
_sym_db.RegisterMessage(GetUsersResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=27
  _USER._serialized_end=68
  _CREATEUSERREQUEST._serialized_start=70
  _CREATEUSERREQUEST._serialized_end=157
  _CREATEUSERRESULT._serialized_start=159
  _CREATEUSERRESULT._serialized_end=204
  _GETUSERSREQUEST._serialized_start=206
  _GETUSERSREQUEST._serialized_end=250
  _GETUSERSRESULT._serialized_start=252
  _GETUSERSRESULT._serialized_end=295
# @@protoc_insertion_point(module_scope)
